service: my-todo-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'local'}
  region: us-east-1
  environment:
    TODOS_TABLE: ${self:service}-${opt:stage, 'local'}
    IS_OFFLINE: '${opt:stage, "local"} == "local" ? "true" : "false"'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:Query
      Resource:
        - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TODOS_TABLE}

custom:
  IS_OFFLINE: '${opt:stage, "local"} == "local" ? "true" : "false"'
  dynamodb:
    stages:
      - local
    start:
      port: 8000
      inMemory: true
      migrate: true
  serverless-offline:
    httpPort: 3000

plugins:
  - serverless-offline
  - serverless-dynamodb

functions:
  createTodo:
    handler: src/handlers/createToDo.handler
    events:
      - http:
          path: todos
          method: post
          cors: true
  getTodos:
    handler: src/handlers/getTodos.handler
    events:
      - http:
          path: todos
          method: get
          cors: true
  updateTodo:
    handler: src/handlers/updateTodo.handler
    events:
      - http:
          path: todos/{id}
          method: put
          cors: true
  deleteTodo:
    handler: src/handlers/deleteTodo.handler
    events:
      - http:
          path: todos/{id}
          method: delete
          cors: true

resources:
  Resources:
    TodosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TODOS_TABLE}
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
